#!/usr/bin/env bash
# Select or restore the persistent form-factor and GPU profile.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
. "$REPO/scripts/lib/install-common.sh"

PROFILE_STATE="$HV_STATE_HOME/hardware-profile.conf"
FORM_FACTOR=
GPU=
ENSURE=0
STATE_INVALID=0

usage() {
    cat <<'EOF'
Usage: 06-select-profile.sh [--ensure] [--form-factor desktop|laptop] [--gpu intel|amd|nvidia]

With --ensure, an existing choice is restored without prompting or changing it.
Passing either profile option is an explicit request to update the saved choice.
Without a saved or passed value, form factor and GPU are auto-detected (battery
presence, lspci) and only need confirmation, not typing.
EOF
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --ensure) ENSURE=1 ;;
        --form-factor) shift; FORM_FACTOR=${1:-} ;;
        --gpu) shift; GPU=${1:-} ;;
        -h|--help) usage; exit 0 ;;
        *) printf 'Unknown argument: %s\n' "$1" >&2; usage >&2; exit 2 ;;
    esac
    shift
done

valid_form() { [[ "$1" = desktop || "$1" = laptop ]]; }
valid_gpu() { [[ "$1" = intel || "$1" = amd || "$1" = nvidia ]]; }

# A BAT* power supply is the same laptop signal docs/HARDWARE.md and the
# Waybar battery helper already rely on.
detect_form_factor() {
    shopt -s nullglob
    local batteries=("${HYPRVEIL_SYSFS_ROOT:-/sys}"/class/power_supply/BAT*)
    shopt -u nullglob
    if [ "${#batteries[@]}" -gt 0 ]; then
        printf 'laptop\n'
    else
        printf 'desktop\n'
    fi
}

# Hybrid laptops report both an Intel and a discrete GPU; the discrete one is
# what actually needs a GPU-specific path, so it wins.
detect_gpu() {
    command -v lspci >/dev/null 2>&1 || return 1
    local vendors
    vendors=$(lspci -mm 2>/dev/null \
        | awk -F '"' '$2 ~ /VGA compatible controller|3D controller|Display controller/ {print $4}')
    [ -n "$vendors" ] || return 1
    case "$vendors" in
        *NVIDIA*) printf 'nvidia\n'; return 0 ;;
    esac
    case "$vendors" in
        *"Advanced Micro Devices"*|*ATI*) printf 'amd\n'; return 0 ;;
    esac
    case "$vendors" in
        *Intel*) printf 'intel\n'; return 0 ;;
    esac
    return 1
}

load_saved() {
    local saved_form='' saved_gpu=''
    if [ -f "$PROFILE_STATE" ]; then
        while IFS='=' read -r key value; do
            case "$key" in
                form_factor) saved_form=$value ;;
                gpu) saved_gpu=$value ;;
            esac
        done < "$PROFILE_STATE"
        if ! valid_form "$saved_form" || ! valid_gpu "$saved_gpu"; then STATE_INVALID=1; fi
        if [ -z "$FORM_FACTOR" ] && valid_form "$saved_form"; then FORM_FACTOR=$saved_form; fi
        if [ -z "$GPU" ] && valid_gpu "$saved_gpu"; then GPU=$saved_gpu; fi
    fi
}

load_saved

if [ "$ENSURE" -eq 1 ] && valid_form "$FORM_FACTOR" && valid_gpu "$GPU"; then
    printf 'Keeping saved hardware profile: %s / %s\n' "$FORM_FACTOR" "$GPU"
fi

if ! valid_form "$FORM_FACTOR"; then
    if [ ! -t 0 ]; then
        printf 'No saved form-factor profile; pass --form-factor desktop|laptop.\n' >&2
        exit 2
    fi
    detected=$(detect_form_factor || true)
    if valid_form "$detected" && hv_confirm "Detected form factor: $detected. Use this?"; then
        FORM_FACTOR=$detected
    else
        read -r -p 'Form factor (desktop/laptop): ' FORM_FACTOR
    fi
fi
if ! valid_gpu "$GPU"; then
    if [ ! -t 0 ]; then
        printf 'No saved GPU profile; pass --gpu intel|amd|nvidia.\n' >&2
        exit 2
    fi
    detected=$(detect_gpu || true)
    if valid_gpu "$detected" && hv_confirm "Detected GPU: $detected. Use this?"; then
        GPU=$detected
    else
        read -r -p 'GPU path (intel/amd/nvidia): ' GPU
    fi
fi
valid_form "$FORM_FACTOR" || { printf 'Invalid form factor: %s\n' "$FORM_FACTOR" >&2; exit 2; }
valid_gpu "$GPU" || { printf 'Invalid GPU profile: %s\n' "$GPU" >&2; exit 2; }

mkdir -p "$HV_STATE_HOME"
if [ "$STATE_INVALID" -eq 1 ]; then
    invalid_backup="$PROFILE_STATE.invalid-$(date +%Y%m%d-%H%M%S)"
    cp -a "$PROFILE_STATE" "$invalid_backup"
    printf 'Malformed prior profile preserved at %s\n' "$invalid_backup" >&2
fi
state_tmp=$(mktemp "$HV_STATE_HOME/.hardware-profile.XXXXXX")
printf 'form_factor=%s\ngpu=%s\n' "$FORM_FACTOR" "$GPU" > "$state_tmp"
chmod 600 "$state_tmp"
mv -f "$state_tmp" "$PROFILE_STATE"

active="$HV_CONFIG_HOME/hypr/profiles/active.conf"
if [ -d "$HV_CONFIG_HOME/hypr/profiles" ]; then
    active_tmp=$(mktemp "$HV_CONFIG_HOME/hypr/profiles/.active.XXXXXX")
    {
        printf '# Generated by scripts/06-select-profile.sh; change the saved choice through that script.\n'
        printf 'source = ~/.config/hypr/profiles/form-factor/%s.conf\n' "$FORM_FACTOR"
        printf 'source = ~/.config/hypr/profiles/gpu/%s.conf\n' "$GPU"
    } > "$active_tmp"
    mv -f "$active_tmp" "$active"
else
    printf 'Profile saved. Install configs to generate %s.\n' "$active"
fi

printf 'Hardware profile selected: %s / %s\n' "$FORM_FACTOR" "$GPU"
if [ "$GPU" = nvidia ]; then
    printf 'NVIDIA selected; no NVIDIA environment workaround was enabled. See docs/HARDWARE.md.\n'
fi
