#!/usr/bin/env bash
# Persist and activate Hyprveil's standard or reduced motion profile.
set -euo pipefail

STATE_HOME="${HYPRVEIL_STATE_HOME:-${XDG_STATE_HOME:-$HOME/.local/state}/hyprveil}"
CONFIG_HOME="${HYPRVEIL_CONFIG_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}}"
STATE_FILE="$STATE_HOME/motion-profile"
MOTION_DIR="$CONFIG_HOME/hypr/motion"
ACTIVE_FILE="$MOTION_DIR/active.conf"

usage() {
    cat <<'EOF'
Usage: motion-profile.sh standard|reduced
       motion-profile.sh --ensure

The choice is saved in $XDG_STATE_HOME/hyprveil/motion-profile and Hyprland is
reloaded when a running session is available.
EOF
}

valid_profile() { [[ "$1" = standard || "$1" = reduced ]]; }

saved_profile() {
    local profile=
    if [ -r "$STATE_FILE" ]; then
        IFS= read -r profile < "$STATE_FILE" || true
    fi
    valid_profile "$profile" && printf '%s\n' "$profile"
}

backup_invalid() {
    local stamp backup suffix=0
    [ -e "$STATE_FILE" ] || return 0
    if saved_profile >/dev/null; then
        return 0
    fi
    stamp=$(date +%Y%m%d-%H%M%S)
    backup="$STATE_FILE.invalid-$stamp"
    while [ -e "$backup" ]; do
        suffix=$((suffix + 1))
        backup="$STATE_FILE.invalid-$stamp-$suffix"
    done
    cp -a "$STATE_FILE" "$backup"
    printf 'Malformed motion state preserved at %s\n' "$backup" >&2
}

write_state() {
    local profile=$1 tmp
    mkdir -p "$STATE_HOME"
    tmp=$(mktemp "$STATE_HOME/.motion-profile.XXXXXX")
    printf '%s\n' "$profile" > "$tmp"
    chmod 600 "$tmp"
    mv -f "$tmp" "$STATE_FILE"
}

write_active() {
    local profile=$1 tmp
    if [ ! -d "$MOTION_DIR" ]; then
        printf 'Motion profile saved. Install configs to activate it.\n'
        return 0
    fi
    [ -f "$MOTION_DIR/$profile.conf" ] || {
        printf 'Missing motion profile: %s\n' "$MOTION_DIR/$profile.conf" >&2
        return 1
    }
    tmp=$(mktemp "$MOTION_DIR/.active.XXXXXX")
    {
        printf '# Generated by motion-profile.sh; use that helper to switch profiles.\n'
        printf 'source = ~/.config/hypr/motion/%s.conf\n' "$profile"
    } > "$tmp"
    mv -f "$tmp" "$ACTIVE_FILE"
}

requested=${1:-}
case "$requested" in
    standard|reduced) profile=$requested; explicit=1 ;;
    --ensure)
        profile=$(saved_profile || printf 'standard\n')
        explicit=0
        ;;
    -h|--help) usage; exit 0 ;;
    *) usage >&2; exit 2 ;;
esac

previous=$(saved_profile || printf 'standard\n')
backup_invalid
if [ -d "$MOTION_DIR" ] && [ ! -f "$MOTION_DIR/$profile.conf" ]; then
    printf 'Missing motion profile: %s\n' "$MOTION_DIR/$profile.conf" >&2
    exit 1
fi
write_state "$profile"
write_active "$profile"

if [ "$explicit" -eq 1 ] && command -v hyprctl >/dev/null 2>&1 \
    && [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; then
    if ! hyprctl reload >/dev/null; then
        printf 'Hyprland rejected the %s profile; restoring %s.\n' "$profile" "$previous" >&2
        write_state "$previous"
        write_active "$previous"
        hyprctl reload >/dev/null 2>&1 || true
        exit 1
    fi
fi

printf 'Motion profile selected: %s\n' "$profile"
